var locations = [
					"Bangalore",
					"Beijing",
					"Bucharest",
					"Budapest",
					"Dubai",
					"Frankfurt",
					"Gdynia",
					"Hong Kong",
					"London",
					"Manila",
					"Mexico City",
					"Milan",
					"Miskolc",
					"Nairobi",
					"New York",
					"Paris",
					"Richardson",
					"Sao Paolo",
					"Shanghai",
					"Singapore",
					"Sydney",
					"Taipei",
					"Tokyo",
					"Warsaw"
];